apiVersion: v1
kind: Pod
metadata:
  labels:
    app: lab2
  name: lab2
  namespace: lab2
spec:
  containers:
    - image: dgreenstein/lab1:1.0.0
      imagePullPolicy: Always
      name: lab2
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
